# Generated by Django 5.2.8 on 2025-11-27 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piapprojeto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil do Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AlterModelOptions(
            name='tarefa',
            options={'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
    ]
