# Generated by Django 5.2.8 on 2025-11-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piapprojeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='dificuldade',
            field=models.CharField(choices=[('F', 'Fácil'), ('M', 'Média'), ('D', 'Difícil')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
