# Generated by Django 6.0 on 2025-12-04 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piapprojeto', '0002_alter_perfilusuario_options_alter_tarefa_options'),
        ('piapprojeto', '0002_perfilusuario_level_tarefa_deleted_at_and_more'),
    ]

    operations = [
    ]
