# Generated by Django 6.0 on 2025-12-04 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piapprojeto', '0003_merge_20251204_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='is_deleted',
        ),
    ]
