# Generated by Django 6.0 on 2025-12-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piapprojeto', '0004_remove_tarefa_deleted_at_remove_tarefa_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='lixeira',
            field=models.BooleanField(default=False),
        ),
    ]
